### ISSUE TITLE
Should 'mutating' operations be mut even if they could be shared (immut)?

### ISSUE THREAD

**Issue by Restioson** [Restioson/flower#35]
I was thinking -- should methods like `write` on `IOPort` take `&mut`? They don't necessarily need to, but it does signal to the user that it mutates an internal state. Opinions?

**Comment by gegy1000** [comment]
Yes.

**Comment by Restioson** [comment]
@CryZe said on the discord that it shouldn't unless it needs exclusive access to itself, which is what &mut really means.

**Comment by Lokathor** [comment]
Things with mutation, either on the rust side or on the far side of some FFI bound, should require &mut instead of & whenever possible. It signals the correct limitations to the API user.

However, you should also explain in the docs that the mut limit is artificial in some sense in the docs, and provide a way to bypass the abstraction's limits. Probably as an unsafe unwrapper or something of the sort.

**Comment by CryZe** [comment]
Choosing your reference type based on the situation:

&mut T:
 - Unsynchronized Writing & Reading
 - Other guard like situations requiring unique access

&T:
 - Synchronized Writing
 - Synchronized Reading
 - Unsynchronized Reading

While the unsynchronized cases nicely match up with &mut T being mutable access and &T being shared access, this largely breaks down once any synchronization (even single threaded) comes into play.

While it is nice to use &mut T / &T to show whether you are mutating, it often just doesn‘t match up with what‘s actually happening as both of them can mutate and both of them might not mutate. For Memory Safety, the only important aspect for Rust, is being able to distinguish exclusive access vs. shared access, as shared access is highly dangerous (especially when writing) and therefore often requires synchronization. However exclusive access means you can do anything without needing to synchronize at all. You can even skip through a Mutex or RwLock completely then, without needing to lock it at all. This is a very strong guarantee. However that truly means that Rust absolutely needs to ensure that you truly have exclusive access, otherwise accessing data through a lock, without locking the lock would be really dangerous. And that therefore comes with a ton of type system limitations for your &mut T, which means you really should only use it, when you actually require this exclusivity guarantee.

So overall, while it is nice to be able to distinguish mutable access and immutable access in the public API, &T could still mutate, and &mut T could not mutate (and is also very limiting for the user of the API). Therefore the only good distinction is the exclusive vs. shared one, which is the only one relevant to ensure memory safety, so it‘s the only distinction the language itself actually cares about.

**Comment by Restioson** [comment]
I think I follow you here. Your argument does make sense. While it is nice to be able to use &mut for mutating operations, maybe that is not the correct thing to do. That still leaves us with whether writes to io ports should be &mut or just & -- although a write can be done in a single instruction and we could just assume that that makes it atomic and safe, we have to consider interrupts and other things. Thoughts on that, anyone?   

(Linked by @CryZe in discord -
 http://smallcultfollowing.com/babysteps/blog/2014/05/13/focusing-on-ownership/)

**Comment by Restioson** [comment]
Closing in favour of @CryZe's solution.
